[env:nodemcu32s]
platform = espressif32
board = nodemcu-32s
framework = arduino
monitor_speed = 115200
lib_deps =
    fastled/FastLED @ ^3.6.0
    h2zero/NimBLE-Arduino @ 2.5.1
    bblanchon/ArduinoJson @ ^7.0.4
    adafruit/Adafruit NeoPixel @ ^1.12.3