#ifndef CONFIG_H
#define CONFIG_H

#define SERIAL_BAUD 115200

// Relay Pins
#define PIN_RELAY_LOCK_A 16
#define PIN_RELAY_LOCK_B 17
#define PIN_RELAY_IGNITION 18
#define PIN_RELAY_STARTER 19
#define PIN_RELAY_HEADLIGHTS 20
#define PIN_RELAY_ACCESSORIES 21
#define PIN_RELAY_HORN 22

// RGB Hardware
#define PIN_RGB_DATA 5
#define NUM_LEDS 14
#define RGB_BRIGHTNESS_DEFAULT 75 // ~30% of 255

#endif // CONFIG_H